var isTrue = true;
var isFalse = false;
console.log("Boolean Examples:");
console.log('isTrue:', isTrue);
console.log('isFalse:', isFalse);
var anyValue = 5;
console.log("\nAny Example:");
console.log('anyValue:', anyValue);
var stringArray = ["apple", "banana", "cherry"];
console.log("\nArray of String Example:");
console.log('stringArray:', stringArray);
var heterogeneousArray = ["apple", 10, true];
console.log("\nHeterogeneous Array Example:");
console.log('heterogeneousArray:', heterogeneousArray);
